import AppForgeDomain
import Foundation

struct FlutterProjectCoreSources {
    let specification: ProjectSpecification
    let graph: ResolvedProductGraph
    let lockfile: ForgeLockfile
    let packageName: String

    func files() throws -> [GeneratedFile] {
        let lockfileData = try ForgeLockfileCodec().encode(lockfile)
        guard let lockfileText = String(data: lockfileData, encoding: .utf8) else {
            throw FlutterRendererError.encodingFailed
        }

        return [
            GeneratedFile(relativePath: ".gitignore", contents: gitignore()),
            GeneratedFile(relativePath: "README.md", contents: readme()),
            GeneratedFile(relativePath: "forge.lock", contents: lockfileText),
            GeneratedFile(relativePath: "lib/app.dart", contents: appDart()),
            GeneratedFile(relativePath: "lib/main.dart", contents: mainDart()),
            GeneratedFile(relativePath: "pubspec.yaml", contents: pubspec()),
            GeneratedFile(relativePath: "test/app_smoke_test.dart", contents: smokeTest())
        ] + stateManagementFiles()
    }

    private func stateManagementFiles() -> [GeneratedFile] {
        switch specification.flutterStateManagement {
        case .riverpod, nil:
            []
        case .blocCubit:
            [
                GeneratedFile(
                    relativePath: "lib/core/state/app_cubit.dart",
                    contents: FlutterGeneratedText.lines([
                        "import 'package:flutter_bloc/flutter_bloc.dart';",
                        "",
                        "class AppCubit extends Cubit<bool> {",
                        "  AppCubit() : super(true);",
                        "}",
                        ""
                    ])
                )
            ]
        }
    }

    private func pubspec() -> String {
        let runtimeDependencies = FlutterPubspecDependencies(
            specification: specification
        ).runtimeLines()

        let description = FlutterDartEscaping.yamlQuoted(
            "Generated by AppForge Pro for \(specification.identity.name)."
        )

        return FlutterGeneratedText.lines(
            [
                "name: \(packageName)",
                "description: \(description)",
                "publish_to: \"none\"",
                "version: 0.1.0+1",
                "",
                "environment:",
                "  sdk: \">=3.10.0 <4.0.0\"",
                "  flutter: \">=3.44.0\"",
                "",
                "dependencies:",
                "  flutter:",
                "    sdk: flutter"
            ]
                + runtimeDependencies
                + [
                    "",
                    "dev_dependencies:",
                    "  flutter_test:",
                    "    sdk: flutter",
                    "",
                    "flutter:",
                    "  uses-material-design: true",
                    ""
                ]
        )
    }

    private func mainDart() -> String {
        switch specification.flutterStateManagement {
        case .riverpod:
            FlutterGeneratedText.lines([
                "import 'package:flutter/material.dart';",
                "import 'package:flutter_riverpod/flutter_riverpod.dart';",
                "",
                "import 'app.dart';",
                "",
                "void main() {",
                "  runApp(",
                "    const ProviderScope(",
                "      child: App(),",
                "    ),",
                "  );",
                "}",
                ""
            ])
        case .blocCubit:
            FlutterGeneratedText.lines([
                "import 'package:flutter/material.dart';",
                "import 'package:flutter_bloc/flutter_bloc.dart';",
                "",
                "import 'app.dart';",
                "import 'core/state/app_cubit.dart';",
                "",
                "void main() {",
                "  runApp(",
                "    BlocProvider(",
                "      create: (_) => AppCubit(),",
                "      child: const App(),",
                "    ),",
                "  );",
                "}",
                ""
            ])
        case nil:
            FlutterGeneratedText.lines([
                "import 'package:flutter/material.dart';",
                "",
                "import 'app.dart';",
                "",
                "void main() {",
                "  runApp(const App());",
                "}",
                ""
            ])
        }
    }

    private func appDart() -> String {
        let displayName = specification.design.appDisplayName ?? specification.identity.name
        let escapedName = FlutterDartEscaping.singleQuoted(displayName)

        return FlutterGeneratedText.lines([
            "import 'package:flutter/material.dart';",
            "",
            "class App extends StatelessWidget {",
            "  const App({super.key});",
            "",
            "  @override",
            "  Widget build(BuildContext context) {",
            "    return MaterialApp(",
            "      debugShowCheckedModeBanner: false,",
            "      title: '\(escapedName)',",
            "      home: const _AppHome(),",
            "    );",
            "  }",
            "}",
            "",
            "class _AppHome extends StatelessWidget {",
            "  const _AppHome();",
            "",
            "  @override",
            "  Widget build(BuildContext context) {",
            "    return Scaffold(",
            "      appBar: AppBar(",
            "        title: const Text('\(escapedName)'),",
            "      ),",
            "      body: const Center(",
            "        child: Text('Generated with AppForge Pro'),",
            "      ),",
            "    );",
            "  }",
            "}",
            ""
        ])
    }

    private func smokeTest() -> String {
        let displayName = specification.design.appDisplayName ?? specification.identity.name
        let escapedName = FlutterDartEscaping.singleQuoted(displayName)

        return FlutterGeneratedText.lines([
            "import 'package:flutter_test/flutter_test.dart';",
            "import 'package:\(packageName)/app.dart';",
            "",
            "void main() {",
            "  testWidgets('renders the generated app shell', (tester) async {",
            "    await tester.pumpWidget(const App());",
            "",
            "    expect(find.text('\(escapedName)'), findsOneWidget);",
            "  });",
            "}",
            ""
        ])
    }

    private func gitignore() -> String {
        FlutterGeneratedText.lines([
            ".dart_tool/",
            ".flutter-plugins",
            ".flutter-plugins-dependencies",
            ".packages",
            "build/",
            "coverage/",
            ".idea/",
            ".vscode/",
            ""
        ])
    }

    private func readme() -> String {
        let packageLines = graph.packages
            .map { "- \($0.contract.id.rawValue) @ \($0.contract.version.description)" }
        let resolvedPackages = packageLines.isEmpty ? ["- none"] : packageLines

        let ownershipStatement = "The generated application is normal editable Flutter source code "
            + "and has no runtime dependency on AppForge Pro."

        return FlutterGeneratedText.lines(
            [
                "# \(FlutterDartEscaping.singleLine(specification.identity.name))",
                "",
                "Generated by AppForge Pro.",
                "",
                "## Architecture",
                "",
                "- MVVM",
                "- Feature-First",
                "- Repository Pattern",
                "- Use Cases",
                "- Single Source of Truth",
                "",
                "## Generated package",
                "",
                packageName,
                "",
                "## Resolved Forge packages",
                ""
            ]
                + resolvedPackages
                + [
                    "",
                    ownershipStatement,
                    ""
                ]
        )
    }
}
